[EH] EXPORT_EXCEPTION_HANDLING_HELPERS requires EH
When you pass `EXPORT_EXCEPTION_HANDLING_HELPERS` without enabling
exception handling, it currently crashes with
```console
$ em++ -sEXPORT_EXCEPTION_HANDLING_HELPERS test.cpp -o test.js

error: undefined symbol: $decrementExceptionRefcount (referenced by top-level compiled C/C++ code)
warning: To disable errors for undefined symbols use `-sERROR_ON_UNDEFINED_SYMBOLS=0`
warning: decrementExceptionRefcount may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: $getExceptionMessage (referenced by top-level compiled C/C++ code)
warning: getExceptionMessage may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
error: undefined symbol: $incrementExceptionRefcount (referenced by top-level compiled C/C++ code)
warning: incrementExceptionRefcount may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
```

This PR detects it early and prints a helpful error message before
exiting.