Fix sockets.test_posix_proxy_sockets on Windows (#22471)
Previous PRs #16585, #20256 broke tools/websocket_to_posix_proxy to no
longer compile on Windows with Visual Studio. Fix errors and warnings to
make the test sockets.test_posix_proxy_sockets to pass on Windows again.

CMake Error at CMakeLists.txt:8 (target_link_libraries):
Cannot specify link libraries for target "websocket_to_posix_proxy"
which
  is not built by this project.

websocket_to_posix_proxy.obj : error LNK2001: unresolved external symbol
webSocketSendLock
[C:\emsdk\emscripten\main\out\test\websocket_to_posix_proxy.vcxproj]
    Hint on symbols that are defined and could potentially match:
"struct _RTL_CRITICAL_SECTION webSocketSendLock"
(?webSocketSendLock@@3U_RTL_CRITICAL_SECTION@@A)


C:\emsdk\emscripten\main\tools\websocket_to_posix_proxy\src\websocket_to_posix_proxy.c(117,29):
warning C4244: '=': conversion from 'uint64_t' to 'unsigned int',
possible loss of data


C:\emsdk\emscripten\main\tools\websocket_to_posix_proxy\src\main.cpp(113,12):
warning C4477: 'printf' : format string '%lu' requires an argument of
type 'unsigned long', but variadic argument 1 has type 'uint64_t'
[C:\emsdk\emscripten\main\out\test\websocket_to_posix_proxy.vcxproj]

C:\emsdk\emscripten\main\tools\websocket_to_posix_proxy\src\main.cpp(113,12):
warning C4477: 'printf' : format string '%lu' requires an argument of
type 'unsigned long', but variadic argument 2 has type 'uint64_t'
[C:\emsdk\emscripten\main\out\test\websocket_to_posix_proxy.vcxproj]

C:\emsdk\emscripten\main\tools\websocket_to_posix_proxy\src\main.cpp(190,10):
warning C4477: 'printf' : format string '%lu' requires an argument of
type 'unsigned long', but variadic argument 4 has type 'uint64_t'
[C:\emsdk\emscripten\main\out\test\websocket_to_posix_proxy.vcxproj]

C:\emsdk\emscripten\main\tools\websocket_to_posix_proxy\src\main.cpp(197,14):
warning C4477: 'printf' : format string '%lu' requires an argument of
type 'unsigned long', but variadic argument 1 has type 'uint64_t'
[C:\emsdk\emscripten\main\out\test\websocket_to_posix_proxy.vcxproj]


C:\emsdk\emscripten\main\tools\websocket_to_posix_proxy\src\websocket_to_posix_proxy.c(109,89):
error C2059: syntax error: '}' [C:\emsdk\emscripten\main\out\test\
websocket_to_posix_proxy.vcxproj]

C:\emsdk\emscripten\main\tools\websocket_to_posix_proxy\src\websocket_to_posix_proxy.c(970,41):
error C2059: syntax error: '}' [C:\emsdk\emscripten\main\out\test\
websocket_to_posix_proxy.vcxproj]

C:\emsdk\emscripten\main\tools\websocket_to_posix_proxy\src\websocket_to_posix_proxy.c(1449,38):
error C2059: syntax error: '}' [C:\emsdk\emscripten\main\out\test
\websocket_to_posix_proxy.vcxproj]