Update libunwind from LLVM 20.1.8 to 21.1.8 (#26036)
This updates libunwind from 20.1.8 to LLVM 21.1.8:
https://github.com/llvm/llvm-project/releases/tag/llvmorg-21.1.8

Additional change:
- Add `-Wno-c23-extensions` to libunwind's cflags:
https://github.com/emscripten-core/emscripten/pull/26036/commits/0070206bfc88b0f758b8e9eb3db0c76d69e10cb6
  https://github.com/llvm/llvm-project/pull/125412 removed parameter names
  to suppress `-Wunused-parameter` in their own build system, but this
  causes these errors instead for us:
  ```console
 ../../../system/lib/libunwind/src/Unwind-wasm.c:105:62: error: omitting
the parameter name in a function definition is a C23 extension
[-Werror,-Wc23-extensions]
105 | _LIBUNWIND_EXPORT void _Unwind_SetIP(struct _Unwind_Context *,
uintptr_t) {}
          |
  ```
  This suppresses the warnings.