[CI] Remove `--experimental-wasm-stack-switching` from chrome flags.
It looks like this flag was removed, causing the flags after it to be
ignored:

```
Error: unrecognized flag --experimental-wasm-stack-switching
The remaining arguments were ignored: --experimental-wasm-type-reflection --experimental-wasm-rab-integration
```