Fix for new warnings in test/third_party/freetype. NFC (#18553)
Seems like clang got more strict and this is causing the rollers
to fail:

```
freetype/src/sfnt/ttload.c:983:32: error: using an array subscript expression within 'offsetof' is a Clang extension [-Werror,-Wgnu-offsetof-extensions]
        FT_FRAME_BYTE  ( panose[6] ),
```