test_benchmark.py: Remove run_binaryen_opts
I noticed this function was completely broken since `--all-features`
was being included in the executable name

If this function was ever run it would crash with:

```
NotADirectoryError: [Errno 20] Not a directory: '/usr/local/google/home/sbc/dev/wasm/binaryen-out/bin/wasm-opt/--all-features'
```

Rather than fixing it, since its completely unused, we can just remove
this feature.