Add -Wno-c23-extensions to libunwind cflags
https://github.com/llvm/llvm-project/pull/125412 removed parameter names
to suppress `-Wunused-parameter` in their own build system. As a result
now we have this error:
```console
../../../system/lib/libunwind/src/Unwind-wasm.c:105:62: error: omitting the parameter name in a function definition is a C23 extension [-Werror,-Wc23-extensions]
  105 | _LIBUNWIND_EXPORT void _Unwind_SetIP(struct _Unwind_Context *, uintptr_t) {}
      |
```

We have three ways to fix it?
1. Re-add parameter names. But this will later clash with
   https://github.com/llvm/llvm-project/pull/125412.
2. Add `-std=c23` to the cflags. But this only applies to .c files and
   our `get_cflags` function in `system_libs.py` doesn't take a file
   name so we can't apply different cflags depending on the file
   extensions. While it's possible to add the filename paramater to
   `get_cflags`, it is a bigger refactoring.
3. Suppress the warning using `-Wno-c23-extension`.

This does 3, which is the quickest. But eventually we may need to change
what https://github.com/llvm/llvm-project/pull/125412 did.