Fix CI bustage due to pip (#6450)
Somehow, pip started to fail on both travis and circle today,

Collecting pip
  Downloading https://files.pythonhosted.org/packages/62/a1/0d452b6901b0157a0134fd27ba89bf95a857fbda64ba52e1ca2cf61d8412/pip-10.0.0-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 1.2MB/s 
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python3/dist-packages, outside environment /usr
Successfully installed pip-10.0.0
Traceback (most recent call last):
  File "/usr/bin/pip3", line 9, in <module>
    from pip import main
ImportError: cannot import name 'main'

This PR fixes the bustage as follows: It seems we only use pip to get lit, and we need that for just one test, other.test_llvm_lit. It's a low-priority test as it's only needed for asm.js backend changes. This PR disables the test and removes pip.