embuilder: if EMCC_WASM_BACKEND, omit tasks using pthreads from ALL (#5107)
* embuilder: if EMCC_WASM_BACKEND, omit tasks using pthreads from ALL

Fixes the following error:

    $ EMCC_WASM_BACKEND=1 ./embuild build ALL
    Traceback (most recent call last):
      File "emscripten/src/emscripten-1.37.9/emcc", line 13, in <module>
        emcc.run()
      File "emscripten/src/emscripten-1.37.9/emcc.py", line 1278, in run
        assert not shared.Settings.USE_PTHREADS, 'WebAssembly does not support pthreads'
    AssertionError: WebAssembly does not support pthreads

* Add myself to AUTHORS