Create separate code path for testing JS vs running JS tools (#7184)
* Create separate process for testing and JS and running JS tools

The `jsrun.run_js()` method has a lot of extra complexity that we
don't need when running, for example, the js compiler.

This change also makes the output much nicer when the JS compiler
fails.

Before:

```
$ ./emcc.py -s IN_TEST_HARNESS=1 /tmp/emscripten_test/hello_file.cpp -o test.html -s ASMFS=1 -s WASM=0 -s USE_PTHREADS=1 -s FETCH_DEBUG=1 -s PROXY_TO_PTHREAD=1 -s WASM=0   -s ERROR_ON_UNDEFINED_SYMBOLS=1
error: unresolved symbol: pthread_mutex_lock
error: unresolved symbol: pthread_mutex_unlock
Aborting compilation due to previous errors | undefined
Traceback (most recent call last):
  File "./emcc.py", line 3074, in <module>
    sys.exit(run())
  File "./emcc.py", line 1790, in run
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tools/shared.py", line 2259, in emscripten
    emscripten._main(cmdline)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/emscripten.py", line 2239, in _main
    return temp_files.run_and_clean(lambda: main(
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tools/tempfiles.py", line 98, in run_and_clean
    return func()
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/emscripten.py", line 2244, in <lambda>
    DEBUG=DEBUG,
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/emscripten.py", line 2170, in main
    temp_files=temp_files, DEBUG=DEBUG)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/emscripten.py", line 91, in emscript
    glue, forwarded_data = compiler_glue(metadata, libraries, compiler_engine, temp_files, DEBUG)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/emscripten.py", line 223, in compiler_glue
    glue, forwarded_data = compile_settings(compiler_engine, libraries, temp_files)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/emscripten.py", line 535, in compile_settings
    cwd=path_from_root('src'), error_limit=300)
  File "/usr/local/google/home/sbc/dev/wasm/emscripten/tools/jsrun.py", line 137, in run_js
    raise Exception('Expected the command ' + str(command) + ' to finish with return code ' + str(assert_returncode) + ', but it returned with code ' + str(proc.returncode) + ' instead! Output: ' + str(ret)[:error_limit])
Exception: Expected the command ['/usr/local/google/home/sbc/bin/node-v8.9.3-linux-x64/bin/node', '/usr/local/google/home/sbc/dev/wasm/emscripten/src/compiler.js', '/tmp/tmpdx7Lpl.txt', '/usr/local/google/home/sbc/dev/wasm/emscripten/src/library_fetch.js', '/usr/local/google/home/sbc/dev/wasm/emscripten/src/library_pthread.js'] to finish with return code 0, but it returned with code 1 instead! Output: // Copyright 2010 The Emscripten Authors.  All rights reserved.
// Emscripten is available under two separate licenses, the MIT license and the
// University of Illinois/NCSA Open Source License.  Both these licenses can be
// found in the LICENSE file.

// The Module object: Our interface to the ou
```

After:

```
$ ./emcc.py -s IN_TEST_HARNESS=1 /tmp/emscripten_test/hello_file.cpp -o test.html -s ASMFS=1 -s WASM=0 -s USE_PTHREADS=1 -s FETCH_DEBUG=1 -s PROXY_TO_PTHREAD=1 -s WASM=0   -s ERROR_ON_UNDEFINED_SYMBOLS=1
error: unresolved symbol: pthread_mutex_lock
error: unresolved symbol: pthread_mutex_unlock
Aborting compilation due to previous errors | undefined
ERROR:root:'/usr/local/google/home/sbc/bin/node-v8.9.3-linux-x64/bin/node /usr/local/google/home/sbc/dev/wasm/emscripten/src/compiler.js /tmp/tmpwWpaGd.txt /usr/local/google/home/sbc/dev/wasm/emscripten/src/library_fetch.js /usr/local/google/home/sbc/dev/wasm/emscripten/src/library_pthread.js' failed (1)
```

* feedback + fixes