Temporarily disable test_metadce_hello_main_module_2
This test needs to be disaled so that a recent llvm change
can roll: https://reviews.llvm.org/D93066

It causes the following diff/failure:

```
AssertionError: Unexpected difference:
--- /b/s/w/ir/k/install/emscripten/tests/other/metadce/hello_world_O3_MAIN_MODULE_2.funcs
+++ /b/s/w/ir/k/install/emscripten/tests/other/metadce/hello_world_O3_MAIN_MODULE_2.funcs.new
@@ -4,7 +4,8 @@
 $__overflow
 $__stdio_write
 $__towrite
-$__wasm_apply_relocs
+$__wasm_apply_data_relocs
+$__wasm_apply_global_relocs
 $__wasm_call_ctors
 $dlmalloc
 $fwrite
```