Make benchmarks using library_browser.js work (#17920)
`test_foreign_functions`, `test_native_functions`, and
`test_native_function_pointers` use
https://github.com/emscripten-core/emscripten/blob/main/test/benchmark_ffis.cpp,
which uses `emscripten_set_main_loop` and `emscripten_cancel_main_loop`:
https://github.com/emscripten-core/emscripten/blob/b8ad2b5b1dfefd4b18f705427f2954623d5f4672/test/benchmark_ffis.cpp#L93-L95
https://github.com/emscripten-core/emscripten/blob/b8ad2b5b1dfefd4b18f705427f2954623d5f4672/test/benchmark_ffis.cpp#L105-L107

This requires `MINIMAL_RUNTIME=0`, but `EmscriptenBenchmarker::build`
sets it by default:
https://github.com/emscripten-core/emscripten/blob/b8ad2b5b1dfefd4b18f705427f2954623d5f4672/test/test_benchmark.py#L216

So they generate this error:
```
error: undefined symbol: emscripten_cancel_main_loop (referenced by top-level compiled C/C++ code)
```

This PR overrides `MINIMAL_RUNTIME` to 0 for those three benchmarks.