Fix get_library() to work with native mode (#17909)
When `get_library`'s `native` parameter is `True`, `emcc_args` should
not be used, because they can be emcc-only args and not clang args. For
example, currently we have
https://github.com/emscripten-core/emscripten/blob/929a6d5810908065bf23aa2af492da32ab572d57/test/common.py#L489
And `-Wno-limited-postlink-optimizations` only exists in emscripten, so
it errors out when directly fed to clang.

So all `NativeBenchmarker` tests fail when calling `lib_builder`,
https://github.com/emscripten-core/emscripten/blob/929a6d5810908065bf23aa2af492da32ab572d57/test/test_benchmark.py#L141
which calls `get_library`, e.g.
https://github.com/emscripten-core/emscripten/blob/929a6d5810908065bf23aa2af492da32ab572d57/test/test_benchmark.py#L994
with the clang error message
```
error: unknown warning option '-Wno-limited-postlink-optimizations'; did
you mean '-Wno-invalid-partial-specialization'?
[-Werror,-Wunknown-warning-option]
```

This uses `emcc_arg` only in the case of non-native builds. Currently
`test_zzz_box2d`, `test_zzz_bullet`, `test_zzz_coremark`, and
`_test_zzz_zlib` are failing and run OK with this PR.