Handle NaN return from JS date.getTime. NFC
This is always wrong even with wasm32 but showed up as JS exception
under wasm64:

```
RangeError: The number NaN cannot be converted to a BigInt because it is not an integer
```

Supercedes: #19952 #19966