select: remove the word "eval." from the comment
This is needed to avoid the following test failure.

> AssertionError: Expected to NOT find 'eval.

Signed-off-by: Kohei Tokunaga <ktokunaga.mail@gmail.com>