CI: Remove --no-wasm-disable-structured-cloning chrome flag. NFC
This flag no longer seem to be recognized and is generating the
following in the CI logs:

```
Error: unrecognized flag --no-wasm-disable-structured-cloning
Try --help for options
```