Build regal with -Wno-nonnull
As of LLVM 21 (https://github.com/llvm/llvm-project/pull/122790),
libcxx's `std::basic_string`'s constructor is marked as `_Nonnull`:
https://github.com/llvm/llvm-project/blob/2078da43e25a4623cab2d0d60decddf709aaea28/libcxx/include/string#L1061
https://github.com/llvm/llvm-project/blob/2078da43e25a4623cab2d0d60decddf709aaea28/libcxx/include/__config#L1252

Comiling this with LLVM 21's libcxx errors out with:
```console
../emscripten/cache/ports/regal/regal-version_7/src/boost/boost/print/string_list.hpp:281:46: error:
      null passed to a callee that requires a non-null argument
      [-Werror,-Wnonnull]
  281 |   PushBack(*this).assign(string ? string : T(NULL));
      |                                              ^~~~
../emscripten/cache/sysroot/include/unistd.h:33:14: note:
      expanded from macro 'NULL'
   33 | #define NULL 0L
```

This suppresses the warnings.