Fix crash on missing linker flags (#23461)
Without this change running `emcc test/hello_world.c -Xlinker` will
crash with:

```
...
  File "emcc.py", line 813, in phase_setup
    state.add_link_flag(i + 1, newargs[i + 1])
                               ~~~~~~~^^^^^^^
IndexError: list index out of range
```