Skip python3 tests on python3.4 and below (#7098)
We don't currently support python3.4 since it doesn't support
circular dependencies in the way that we use them.  Currently
it generates:

```
Traceback (most recent call last):
  File "/b/build/slave/linux/build/src/src/work/wasm-install/emscripten/tools/cache.py", line 136, in <module>
    from . import shared
ImportError: cannot import name 'shared'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/b/build/slave/linux/build/src/src/work/wasm-install/emscripten/emcc.py", line 38, in <module>
    from tools import shared, jsrun, system_libs, client_mods, js_optimizer
  File "/b/build/slave/linux/build/src/src/work/wasm-install/emscripten/tools/shared.py", line 21, in <module>
    from . import jsrun, cache, tempfiles, colored_logger
  File "/b/build/slave/linux/build/src/src/work/wasm-install/emscripten/tools/cache.py", line 139, in <module>
    import shared
ImportError: No module named 'shared'
```