[embind] Handle -fno-exceptions and try/catch redefinition macros.
When some code bases disable exceptions they also redefine try/catch
with preprocessor macros. This causes the val coroutine function
`unhandled_exception` to fail to compile with
`error: use of undeclared identifier 'error'`.