Don't build libwasm_workers_stubs with -pthread. NFC
With #17914, libwasm_workers was built with `-flto` in LTO mode (just
like most other standard libraries).  However doing seemed to trigger
a bug which was that libwasm_workers was being built with `-pthread`
even when pthreads were not enabled.  Somehow this didn't matter before
but once it was also built with LTO it caused a failure on one of our
bots:

```
FAIL: test_dylink_syslibs_all (test_core.lto2)
CompileError: WebAssembly.instantiate(): Compiling function #923:"emscripten_atomic_cas_u32" failed: Invalid opcode (enable with --experimental-wasm-threads) @+640479
Aborted(CompileError: WebAssembly.instantiate(): Compiling function #923:"emscripten_atomic_cas_u32" failed: Invalid opcode (enable with --experimental-wasm-threads) @+640479)
```